name: Cache query compilation
description: Caches CodeQL compilation caches - should be run both on PRs and pushes to main.

inputs:
  key:
    description: 'The cache key to use - should be unique to the workflow'
    required: true

outputs:
  cache-dir:
    description: "The directory where the cache was stored"
    value: ${{ steps.fill-compilation-dir.outputs.compdir }}

runs:
  using: composite
  steps:
    # calculate the merge-base with main, in a way that works both on PRs and pushes to main.
    - name: Calculate merge-base
      shell: bash
      if: ${{ github.event_name == 'pull_request' }}
      env:
        BASE_BRANCH: ${{ github.base_ref }}
      run: |
        MERGE_BASE=$(git cat-file commit $GITHUB_SHA | grep '^parent ' | head -1 | cut -f 2 -d " ")
        echo "merge_base=$MERGE_BASE" >> $GITHUB_ENV
    - name: Restore read-only cache (PR)
      if: ${{ github.event_name == 'pull_request' }}
      uses: erik-krogh/actions-cache@a88d0603fe5fb5606db9f002dfcadeb32b5f84c6
      with:
        path: '**/.cache'
        read-only: true
        key: ${{ inputs.key }}-pr-${{ github.sha }}
        restore-keys: |
          ${{ inputs.key }}-${{ github.base_ref }}-${{ env.merge_base }}
          ${{ inputs.key }}-${{ github.base_ref }}-
          ${{ inputs.key }}-main-
    - name: Fill cache (push)
      if: ${{ github.event_name != 'pull_request' }}
      uses: erik-krogh/actions-cache@a88d0603fe5fb5606db9f002dfcadeb32b5f84c6
      with:
        path: '**/.cache'
        key: ${{ inputs.key }}-${{ github.ref_name }}-${{ github.sha }} # just fill on main
        restore-keys: | # restore the latest cache if the exact cache is unavailable, to speed up compilation.
          ${{ inputs.key }}-${{ github.ref_name }}-
          ${{ inputs.key }}-main-
    - name: Fill compilation cache directory
      id: fill-compilation-dir
      shell: bash
      run: |
        # Move all the existing cache into another folder, so we only preserve the cache for the current queries.
        mkdir -p ${COMBINED_CACHE_DIR}
        rm -f **/.cache/{lock,size} # -f to avoid errors if the cache is empty.
        # copy the contents of the .cache folders into the combined cache folder.
        cp -r **/.cache/* ${COMBINED_CACHE_DIR}/ || : # ignore missing files
        # clean up the .cache folders
        rm -rf **/.cache/*

        echo "compdir=${COMBINED_CACHE_DIR}" >> $GITHUB_OUTPUT
      env:
        COMBINED_CACHE_DIR: ${{ github.workspace }}/compilation-dir
